#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

# Apply Yunohost app's config
ynh_app_config_apply() {
    _ynh_app_config_apply

    artisan="ynh_exec_as_app php$php_version artisan"

    if [[ "${changed[mail_mailer]}" == "true" ]]
    then
        ynh_replace --match="^MAIL_" --replace="# MAIL_" --file=$install_dir/.env
        ynh_replace --match="^MAILGUN" --replace="# MAILGUN" --file=$install_dir/.env
        ynh_replace --match="^POSTMARK" --replace="# POSTMARK" --file=$install_dir/.env
        ynh_replace --match="^RESEND" --replace="# RESEND" --file=$install_dir/.env
        ynh_replace --match="# MAIL_MAILER" --replace="MAIL_MAILER" --file=$install_dir/.env

        if [ $(ynh_app_setting_get --key=mail_mailer) == "smtp" ]
        then
            ynh_replace --match="# MAIL_" --replace="MAIL_" --file=$install_dir/.env
            ynh_write_var_in_file --file=$install_dir/.env --key=MAIL_HOST --value="$(ynh_app_setting_get --key=smtp_host)"
            ynh_write_var_in_file --file=$install_dir/.env --key=MAIL_PORT --value="$(ynh_app_setting_get --key=smtp_port)"
            ynh_write_var_in_file --file=$install_dir/.env --key=MAIL_USERNAME --value="$(ynh_app_setting_get --key=smtp_username)"
            ynh_write_var_in_file --file=$install_dir/.env --key=MAIL_PASSWORD --value="$(ynh_app_setting_get --key=smtp_password)"
            ynh_write_var_in_file --file=$install_dir/.env --key=MAIL_ENCRYPTION --value="$(ynh_app_setting_get --key=smtp_encryption)"
            ynh_write_var_in_file --file=$install_dir/.env --key=MAIL_FROM_ADDRESS --value="$(ynh_app_setting_get --key=smtp_from)"
        elif [ $(ynh_app_setting_get --key=mail_mailer) == "mailgun" ]
        then
            ynh_replace --match="# MAILGUN" --replace="MAILGUN" --file=$install_dir/.env
            ynh_write_var_in_file --file=$install_dir/.env --key=MAILGUN_DOMAIN --value="$(ynh_app_setting_get --key=mailgun_domain)"
            ynh_write_var_in_file --file=$install_dir/.env --key=MAILGUN_SECRET --value="$(ynh_app_setting_get --key=mailgun_secret)"
        elif [ $(ynh_app_setting_get --key=mail_mailer) == "postmark" ]
        then
            ynh_replace --match="# POSTMARK" --replace="POSTMARK" --file=$install_dir/.env
            ynh_write_var_in_file --file=$install_dir/.env --key=POSTMARK_TOKEN --value="$(ynh_app_setting_get --key=postmark_token)"
        elif [ $(ynh_app_setting_get --key=mail_mailer) == "resend" ]
        then
            ynh_replace --match="# RESEND" --replace="RESEND" --file=$install_dir/.env
            ynh_write_var_in_file --file=$install_dir/.env --key=RESEND_KEY --value="$(ynh_app_setting_get --key=resend_key)"
        fi
    fi

    pushd "$install_dir"
        $artisan queue:restart
        $artisan config:clear
        $artisan cache:clear
        $artisan config:cache
        $artisan optimize:clear
        ynh_systemctl --service="php$php_version-fpm" --action="restart"
    popd
}

ynh_app_config_run $1
