#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# ynh_config_remove_fail2ban

ynh_config_remove_logrotate

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi
ynh_config_remove_systemd

ynh_config_remove_nginx

ynh_config_remove_phpfpm

# Remove other various files specific to the app... such as:

ynh_safe_rm "/etc/cron.d/$app"

# Remove Redis Bloom config

if [ -f "$REDIS_CONF" ]; then
    ynh_print_info "Cleaning Redis configuration"
    sed -i '\|redisbloom.so|d' "$REDIS_CONF"
fi

if [ -f "$REDISBLOOM_SO" ]; then
    ynh_print_info "Removing RedisBloom binary"
    ynh_secure_remove "$REDISBLOOM_SO"
fi

ynh_print_info "Restarting Redis"
ynh_systemd_action --service_name=redis-server --action=restart

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
