#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

timezone=$(timedatectl show --value --property=Timezone)
ynh_app_setting_set_default --key=php_upload_max_filesize --value=100M
ynh_app_setting_set_default --key=php_post_max_size --value=100M
ynh_app_setting_set_default --key=php_max_file_uploads --value=100M
ynh_app_setting_set_default --key=php_max_execution_time --value=300
ynh_app_setting_set_default --key=php_memory_limit --value=512M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=".env storage"

chown -R "$app:www-data" "$install_dir"

#=================================================
# COMPOSER
#=================================================
ynh_script_progression "Pulling in external libraries with Composer..."

ynh_composer_exec install --no-dev --optimize-autoloader

#=================================================
# INSTALL NODE DEPENDENCIES
#=================================================
ynh_script_progression "Install Node dependencies..."

pushd "$install_dir"
    ynh_hide_warnings ynh_exec_as_app npm install
    ynh_hide_warnings ynh_exec_as_app npm run build
popd

chown -Rv $app:www-data $install_dir

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

chmod 600 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"

#=================================================
# RUN MIGRATIONS
#=================================================
ynh_script_progression "Running migrations..."

artisan="ynh_exec_as_app php$php_version artisan"

pushd "$install_dir"
    $artisan migrate --force
popd

ynh_script_progression "Clearing and rebuilding caches..."

# Clear caches
pushd "$install_dir"
    $artisan cache:clear
    $artisan config:clear
    $artisan view:clear
popd

# Rebuild caches
pushd "$install_dir"
    $artisan config:cache
    $artisan route:cache
    $artisan view:cache
popd

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="A short description of the app" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

# ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

# Set permissions
sudo chown -R $app:www-data /var/www/loops
sudo chmod -R 775 /var/www/$app/storage
sudo chmod -R 775 /var/www/$app/bootstrap/cache

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
