#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

if ynh_app_upgrading_from_version_before 1.0.0-beta.4~ynh9
then
    ynh_app_setting_set_default --key=app_key --value="$(ynh_read_var_in_file --file=$install_dir/.env --key=APP_KEY)"
fi
ynh_app_setting_set_default --key=app_key --value="$(ynh_read_var_in_file --file=$install_dir/.env --key=MAIL_MAILER)"
if [ $(ynh_read_var_in_file --file=$install_dir/.env --key=MAIL_MAILER) = "mailgun" ]
then
    mailgun_domain=$(grep ^MAILGUN_DOMAIN $install_dir/.env)
    mailgun_secret=$(grep ^MAILGUN_SECRET $install_dir/.env)
elif [ $(ynh_read_var_in_file --file=$install_dir/.env --key=MAIL_MAILER) = "postmark" ]
then
    postmark_token=$(grep ^POSTMARK_TOKEN $install_dir/.env)
elif [ $(ynh_read_var_in_file --file=$install_dir/.env --key=MAIL_MAILER) = "resend" ]
then
    resend_key=$(grep ^RESEND_KEY $install_dir/.env)
fi
elif [ $(ynh_read_var_in_file --file=$install_dir/.env --key=MAIL_MAILER) = "resend" ]
ynh_app_setting_set_default --key=php_upload_max_filesize --value=100M
ynh_app_setting_set_default --key=php_post_max_size --value=100M
ynh_app_setting_set_default --key=php_max_file_uploads --value=100M
ynh_app_setting_set_default --key=php_max_execution_time --value=300
ynh_app_setting_set_default --key=php_memory_limit --value=512M
if [ $s3_path_style -eq 1 ]
then
    s3_path_style_string="true"
else
    s3_path_style_string="false"
fi
ynh_app_setting_set_default --key=s3_path_style_string --value=$s3_path_style_string

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="storage"

#=================================================
# COMPOSER
#=================================================
ynh_script_progression "Pulling in external libraries with Composer..."

ynh_composer_exec install --no-dev --optimize-autoloader

#=================================================
# INSTALL NODE DEPENDENCIES
#=================================================
ynh_script_progression "Install Node dependencies..."

pushd "$install_dir"
    ynh_hide_warnings ynh_exec_as_app npm ci
    ynh_hide_warnings ynh_exec_as_app npm run build
popd

chown -R $app:www-data $install_dir

#=================================================
# APP CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"
ynh_write_var_in_file --file=$install_dir/.env --key=APP_KEY --value="$(ynh_app_setting_get --key=app_key)"

chmod 600 "$install_dir/.env"

#=================================================
# APP CONFIGURATION
#=================================================
ynh_write_var_in_file --file=$install_dir/.env --key=MAIL_MAILER --value="$(ynh_app_setting_get --key=mail_mailer)"
if [ ynh_app_setting_get --key=mail_mailer = "smtp" ]
then
    ynh_write_var_in_file --file=$install_dir/.env --key=MAIL_HOST --value="$(ynh_app_setting_get --key=smtp_host)"
    ynh_write_var_in_file --file=$install_dir/.env --key=MAIL_PORT --value="$(ynh_app_setting_get --key=smtp_port)"
    ynh_write_var_in_file --file=$install_dir/.env --key=MAIL_USERNAME --value="$(ynh_app_setting_get --key=smtp_username)"
    ynh_write_var_in_file --file=$install_dir/.env --key=MAIL_PASSWORD --value="$(ynh_app_setting_get --key=smtp_password)"
    ynh_write_var_in_file --file=$install_dir/.env --key=MAIL_ENCRYPTION --value="$(ynh_app_setting_get --key=smtp_encryption)"
    ynh_write_var_in_file --file=$install_dir/.env --key=MAIL_FROM_ADDRESS --value="$(ynh_app_setting_get --key=smtp_from)"
elif [ ynh_app_setting_get --key=mail_mailer = "mailgun" ]
then
    ynh_hide_warnings ynh_exec_as_app sed -i "59 aMAILGUN_SECRET=$mailgun_secret" $install_dir/.env
    ynh_hide_warnings ynh_exec_as_app sed -i "59 aMAILGUN_DOMAIN=$mailgun_domain" $install_dir/.env
elif [ ynh_app_setting_get --key=mail_mailer = "postmark" ]
then
    ynh_hide_warnings ynh_exec_as_app sed -i "59 aPOSTMARK_TOKEN=$postmark_token" $install_dir/.env
elif [ ynh_app_setting_get --key=mail_mailer = "resend" ]
then
    ynh_hide_warnings ynh_exec_as_app sed -i "59 aRESEND_KEY=$resend_key" $install_dir/.env
fi

#=================================================
# RUN MIGRATIONS
#=================================================
ynh_script_progression "Running migrations..."

artisan="ynh_exec_as_app php$php_version artisan"

pushd "$install_dir"
    $artisan migrate --force
popd

ynh_script_progression "Clearing and rebuilding caches..."


pushd "$install_dir"
    $artisan queue:restart
    # Clear caches
    $artisan cache:clear
    $artisan config:clear
    $artisan view:clear
    $artisan optimize:clear
    # Rebuild caches
    $artisan config:cache
    $artisan route:cache
    $artisan view:cache
popd

# Generate Passport Keys
pushd "$install_dir"
    if [ ! -f storage/oauth-private.key ]
    then
        $artisan passport:keys
    fi
popd

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Federated short video sharing" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

# ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

# Set permissions
chown -R $app:www-data $install_dir
chmod -R 775 $install_dir/storage
chmod -R 775 $install_dir/bootstrap/cache
chmod 660 $install_dir/storage/oauth-p*

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
